### ISSUE TITLE
Problem to docker-composer up

### ISSUE THREAD

**Issue by lotharthesavior** [bluzelle/docker-swarm-deploy#2]
Hello,

I'm struggling to make it work in my environment, not sure what is happening, but after follow all the  procedures in the Quick Start, I'm having the following result on CLI:

> docker-swarm-deploy git:master ❯ docker-compose up
> Recreating docker-swarm-deploy_peers-server_1 ... done
> Attaching to docker-swarm-deploy_peers-server_1
> peers-server_1  | envsubst: error while reading "standard input": Is a directory
> docker-swarm-deploy_peers-server_1 exited with code 1

Obs.: I intentionally, to debug, put to start only the **peers-server_1** this time, because when it fail, all the others return code 1, and stop.

I'm not sure if other people face a similar problem, and if I'm missing some basic step.

Thanks in advance.

**Comment by amastracci** [comment]
What os are you running on?

**Comment by lotharthesavior** [comment]
I’m running on macOS (High Sierra).

**Comment by amastracci** [comment]
I have not seen this issue on High Sierra. I am running:

$ docker -v
Docker version 18.03.0-ce, build 0520e24
$ docker-compose --version
docker-compose version 1.20.1, build 5d8c71b

**Comment by amastracci** [comment]
@lotharthesavior Please pull the latest docker-compose.yml and try again.

**Comment by lotharthesavior** [comment]
@amastracci before everything, thanks for the help.

The peerlist still not working properly in my environment. I tried the latest version at the master branch, and I also checked your PR and placed those changes here to test, but it didn't. It throws the same error.

This peerlist is not a problem when I place it at some other place, like pastebin. When I do it, I start to have something related to "election timer was canceled: Operation canceled", but this is another problem that I didn't have time to verify further yet.

The error "_error while reading "standard input": Is a directory_" seems to be related to the command **envsubst**, but I can't see any problem in the peerlist's Dockerfile.

This is my environment:

$docker -v
Docker version 18.03.1-ce, build 9ee9f40
$ docker-compose -v
docker-compose version 1.21.1, build 5a3f1a3

**Comment by ebruck** [comment]
@lotharthesavior please ignore debug messages. 

> "election timer was canceled: Operation canceled"

This means the election timer was canceled and restarted which is normal.

**Comment by amastracci** [comment]
@lotharthesavior Did you run a "docker-compose pull" to grab the latest patched containers?

**Comment by lotharthesavior** [comment]
@amastracci it worked! Thanks for the help. 

@ebruck Thanks for confirming that it is normal for the election timer canceled.

I believe that we can close this issue :)

Just in case you know something about it: I'm experiencing the exception "Server sent invalid upgrade response" after attempt a connection to another leader (when I receive the another leader information for connection).

**Comment by amastracci** [comment]
Closing issue. @lotharthesavior if the problem you describe continues to impact performance or function then let's track it in another thread.
